# See: https://docs.gitlab.com/ee/ci/yaml/includes.html
image: $SKA_K8S_TOOLS_DEPLOY_IMAGE

variables:
  # make sure the .make submodule is pulled from the ska-cicd-makefile GitLab repository
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - test
  - scan
  - build
  - publish
  - pages

include:
# Python jobs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python.gitlab-ci.yml'

# Documentation jobs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

# Tag-based GitLab release management
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'

# Finaliser job
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'
