"""Test Generating Metadata File."""

import logging
import os

import pytest
import yaml

from ska_sdp_dataproduct_metadata import MetaData

LOG = logging.getLogger("metadata-test")
LOG.setLevel(logging.DEBUG)

PATH_LIST = [
    {"path": "vis.ms", "description": "raw visibilities"},
    {"path": "vis_new.ms", "description": "extra visibilities"},
]
INPUT_FILE = "tests/resources/test_metadata_default.yaml"
OUTPUT_PATH = "tests/resources/temp_output_metadata.yaml"
OUTPUT_METADATA = "tests/resources/expected_metadata.yaml"
OUTPUT_METADATA_WITHOUT_FILES = (
    "tests/resources/expected_metadata_without_files.yaml"
)
OUTPUT_METADATA_WITH_FILES = (
    "tests/resources/expected_metadata_with_files.yaml"
)
UPDATED_METADATA = "tests/resources/expected_updated_metadata.yaml"


def test_create():
    """
    Test the creation of the Metadata file using
    default parameters
    """
    MetaData(
        input_file=INPUT_FILE,
        eb_id="eb-test-20220916-00000",
        pb_id="pb-test-20220916-00000",
        processing_script="vis-receive",
        output_path=OUTPUT_PATH,
    )
    metadata = read_file(OUTPUT_PATH)
    expected_metadata = read_file(OUTPUT_METADATA_WITHOUT_FILES)
    assert metadata == expected_metadata

    # Clean up
    delete_file(OUTPUT_PATH)


def test_update_status():
    """Test updating the status of the files"""
    metadata = MetaData(
        input_file=INPUT_FILE,
        eb_id="eb-test-20220916-00000",
        pb_id="pb-test-20220916-00000",
        processing_script="vis-receive",
        output_path=OUTPUT_PATH,
    )
    metadata.add_path_to_files(PATH_LIST)
    metadata_with_files = read_file(OUTPUT_PATH)
    expected_metadata = read_file(OUTPUT_METADATA_WITH_FILES)
    assert metadata_with_files == expected_metadata

    metadata.update_file_status("vis.ms", "done")
    updated_file = read_file(OUTPUT_PATH)
    expected_update_metadata = read_file(UPDATED_METADATA)
    assert updated_file == expected_update_metadata

    # Clean up
    delete_file(OUTPUT_PATH)


def read_file(file):
    """Read and load files into yaml"""
    with open(file, "r", encoding="utf8") as input_file:
        data = yaml.safe_load(input_file)
    return data


def delete_file(file):
    """Delete output files generated by the tests"""

    LOG.info("I am inside this function")

    if os.path.exists(file):
        os.remove(file)
    else:
        LOG.info("The file does not exist")


def test_create_no_eb_id():
    """
    Check that ValueError is raised when there is no execution block ID"
    """

    with pytest.raises(ValueError, match=r"Execution Block ID is None!"):
        MetaData(
            input_file=INPUT_FILE,
            pb_id="pb-test-20220916-00000",
            processing_script="vis-receive",
            output_path=OUTPUT_PATH,
        )


def test_create_no_pb_id():
    """
    Check that ValueError is raised when there is no processing block ID"
    """

    with pytest.raises(ValueError, match=r"Processing Block ID is None!"):
        MetaData(
            input_file=INPUT_FILE,
            eb_id="eb-test-20220916-00000",
            processing_script="vis-receive",
            output_path=OUTPUT_PATH,
        )


def test_create_no_processing_script():
    """
    Check that ValueError is raised when there is no processing script"
    """

    with pytest.raises(ValueError, match=r"Processing Script is None!"):
        MetaData(
            input_file=INPUT_FILE,
            eb_id="eb-test-20220916-00000",
            pb_id="pb-test-20220916-00000",
            output_path=OUTPUT_PATH,
        )
